#!/bin/sh -
#
# trydhcp script
#

IP=$(getip)

if [[ -z "$IP" ]]; then
	PID=$(cat /var/run/dhcpcd.pid)

	if [[ -n "$PID" ]]; then
		echo `killall -9 dhcpcd`
		sleep 3
	fi

	echo `dhcpcd eth1`
	echo `ifconfig eth1 up`
fi

