#############################################################################
# Makefile for building: gingagui-minipc-cpp
# Generated by qmake (2.01a) (Qt 4.8.2) on: Wed Sep 18 12:24:40 2013
# Project:  gingagui-minipc-cpp.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile gingagui-minipc-cpp.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../../lib64/qt/mkspecs/linux-g++-64 -I. -I../../../../lib64/qt/include/QtCore -I../../../../lib64/qt/include/QtGui -I../../../../lib64/qt/include/QtXml -I../../../../lib64/qt/include -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/usr/lib64/qt/lib
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt/lib -lQtXml -L/usr/lib64/qt/lib -lQtGui -L/usr/X11R6/lib64 -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		page.cpp \
		pagexmlparser.cpp \
		menuitem.cpp \
		gingaproxy.cpp \
		gingapage.cpp \
		infobar.cpp moc_mainwindow.cpp \
		moc_page.cpp \
		moc_menuitem.cpp \
		moc_gingaproxy.cpp \
		moc_gingapage.cpp \
		moc_infobar.cpp \
		qrc_Resources.cpp
OBJECTS       = main.o \
		mainwindow.o \
		page.o \
		pagexmlparser.o \
		menuitem.o \
		gingaproxy.o \
		gingapage.o \
		infobar.o \
		moc_mainwindow.o \
		moc_page.o \
		moc_menuitem.o \
		moc_gingaproxy.o \
		moc_gingapage.o \
		moc_infobar.o \
		qrc_Resources.o
DIST          = ../../../../lib64/qt/mkspecs/common/unix.conf \
		../../../../lib64/qt/mkspecs/common/linux.conf \
		../../../../lib64/qt/mkspecs/common/gcc-base.conf \
		../../../../lib64/qt/mkspecs/common/gcc-base-unix.conf \
		../../../../lib64/qt/mkspecs/common/g++-base.conf \
		../../../../lib64/qt/mkspecs/common/g++-unix.conf \
		../../../../lib64/qt/mkspecs/qconfig.pri \
		../../../../lib64/qt/mkspecs/modules/qt_phonon.pri \
		../../../../lib64/qt/mkspecs/modules/qt_webkit_version.pri \
		../../../../lib64/qt/mkspecs/features/qt_functions.prf \
		../../../../lib64/qt/mkspecs/features/qt_config.prf \
		../../../../lib64/qt/mkspecs/features/exclusive_builds.prf \
		../../../../lib64/qt/mkspecs/features/default_pre.prf \
		../../../../lib64/qt/mkspecs/features/release.prf \
		../../../../lib64/qt/mkspecs/features/default_post.prf \
		../../../../lib64/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../../lib64/qt/mkspecs/features/warn_on.prf \
		../../../../lib64/qt/mkspecs/features/qt.prf \
		../../../../lib64/qt/mkspecs/features/unix/thread.prf \
		../../../../lib64/qt/mkspecs/features/moc.prf \
		../../../../lib64/qt/mkspecs/features/resources.prf \
		../../../../lib64/qt/mkspecs/features/uic.prf \
		../../../../lib64/qt/mkspecs/features/yacc.prf \
		../../../../lib64/qt/mkspecs/features/lex.prf \
		../../../../lib64/qt/mkspecs/features/include_source_dir.prf \
		gingagui-minipc-cpp.pro
QMAKE_TARGET  = gingagui-minipc-cpp
DESTDIR       = 
TARGET        = gingagui-minipc-cpp

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: gingagui-minipc-cpp.pro  ../../../../lib64/qt/mkspecs/linux-g++-64/qmake.conf ../../../../lib64/qt/mkspecs/common/unix.conf \
		../../../../lib64/qt/mkspecs/common/linux.conf \
		../../../../lib64/qt/mkspecs/common/gcc-base.conf \
		../../../../lib64/qt/mkspecs/common/gcc-base-unix.conf \
		../../../../lib64/qt/mkspecs/common/g++-base.conf \
		../../../../lib64/qt/mkspecs/common/g++-unix.conf \
		../../../../lib64/qt/mkspecs/qconfig.pri \
		../../../../lib64/qt/mkspecs/modules/qt_phonon.pri \
		../../../../lib64/qt/mkspecs/modules/qt_webkit_version.pri \
		../../../../lib64/qt/mkspecs/features/qt_functions.prf \
		../../../../lib64/qt/mkspecs/features/qt_config.prf \
		../../../../lib64/qt/mkspecs/features/exclusive_builds.prf \
		../../../../lib64/qt/mkspecs/features/default_pre.prf \
		../../../../lib64/qt/mkspecs/features/release.prf \
		../../../../lib64/qt/mkspecs/features/default_post.prf \
		../../../../lib64/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../../lib64/qt/mkspecs/features/warn_on.prf \
		../../../../lib64/qt/mkspecs/features/qt.prf \
		../../../../lib64/qt/mkspecs/features/unix/thread.prf \
		../../../../lib64/qt/mkspecs/features/moc.prf \
		../../../../lib64/qt/mkspecs/features/resources.prf \
		../../../../lib64/qt/mkspecs/features/uic.prf \
		../../../../lib64/qt/mkspecs/features/yacc.prf \
		../../../../lib64/qt/mkspecs/features/lex.prf \
		../../../../lib64/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt/lib/libQtXml.prl \
		/usr/lib64/qt/lib/libQtCore.prl \
		/usr/lib64/qt/lib/libQtGui.prl
	$(QMAKE) -o Makefile gingagui-minipc-cpp.pro
../../../../lib64/qt/mkspecs/common/unix.conf:
../../../../lib64/qt/mkspecs/common/linux.conf:
../../../../lib64/qt/mkspecs/common/gcc-base.conf:
../../../../lib64/qt/mkspecs/common/gcc-base-unix.conf:
../../../../lib64/qt/mkspecs/common/g++-base.conf:
../../../../lib64/qt/mkspecs/common/g++-unix.conf:
../../../../lib64/qt/mkspecs/qconfig.pri:
../../../../lib64/qt/mkspecs/modules/qt_phonon.pri:
../../../../lib64/qt/mkspecs/modules/qt_webkit_version.pri:
../../../../lib64/qt/mkspecs/features/qt_functions.prf:
../../../../lib64/qt/mkspecs/features/qt_config.prf:
../../../../lib64/qt/mkspecs/features/exclusive_builds.prf:
../../../../lib64/qt/mkspecs/features/default_pre.prf:
../../../../lib64/qt/mkspecs/features/release.prf:
../../../../lib64/qt/mkspecs/features/default_post.prf:
../../../../lib64/qt/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../../lib64/qt/mkspecs/features/warn_on.prf:
../../../../lib64/qt/mkspecs/features/qt.prf:
../../../../lib64/qt/mkspecs/features/unix/thread.prf:
../../../../lib64/qt/mkspecs/features/moc.prf:
../../../../lib64/qt/mkspecs/features/resources.prf:
../../../../lib64/qt/mkspecs/features/uic.prf:
../../../../lib64/qt/mkspecs/features/yacc.prf:
../../../../lib64/qt/mkspecs/features/lex.prf:
../../../../lib64/qt/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt/lib/libQtXml.prl:
/usr/lib64/qt/lib/libQtCore.prl:
/usr/lib64/qt/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile gingagui-minipc-cpp.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/gingagui-minipc-cpp1.0.0 || $(MKDIR) .tmp/gingagui-minipc-cpp1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/gingagui-minipc-cpp1.0.0/ && $(COPY_FILE) --parents mainwindow.h page.h util.h pagexmlparser.h menuitem.h gingaproxy.h gingapage.h infobar.h .tmp/gingagui-minipc-cpp1.0.0/ && $(COPY_FILE) --parents Resources.qrc .tmp/gingagui-minipc-cpp1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp page.cpp pagexmlparser.cpp menuitem.cpp gingaproxy.cpp gingapage.cpp infobar.cpp .tmp/gingagui-minipc-cpp1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/gingagui-minipc-cpp1.0.0/ && (cd `dirname .tmp/gingagui-minipc-cpp1.0.0` && $(TAR) gingagui-minipc-cpp1.0.0.tar gingagui-minipc-cpp1.0.0 && $(COMPRESS) gingagui-minipc-cpp1.0.0.tar) && $(MOVE) `dirname .tmp/gingagui-minipc-cpp1.0.0`/gingagui-minipc-cpp1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/gingagui-minipc-cpp1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_page.cpp moc_menuitem.cpp moc_gingaproxy.cpp moc_gingapage.cpp moc_infobar.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_page.cpp moc_menuitem.cpp moc_gingaproxy.cpp moc_gingapage.cpp moc_infobar.cpp
moc_mainwindow.cpp: gingapage.h \
		infobar.h \
		page.h \
		util.h \
		menuitem.h \
		gingaproxy.h \
		mainwindow.h
	/usr/lib64/qt/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_page.cpp: util.h \
		menuitem.h \
		gingaproxy.h \
		gingapage.h \
		infobar.h \
		page.h
	/usr/lib64/qt/bin/moc $(DEFINES) $(INCPATH) page.h -o moc_page.cpp

moc_menuitem.cpp: menuitem.h
	/usr/lib64/qt/bin/moc $(DEFINES) $(INCPATH) menuitem.h -o moc_menuitem.cpp

moc_gingaproxy.cpp: gingaproxy.h
	/usr/lib64/qt/bin/moc $(DEFINES) $(INCPATH) gingaproxy.h -o moc_gingaproxy.cpp

moc_gingapage.cpp: infobar.h \
		gingapage.h
	/usr/lib64/qt/bin/moc $(DEFINES) $(INCPATH) gingapage.h -o moc_gingapage.cpp

moc_infobar.cpp: infobar.h
	/usr/lib64/qt/bin/moc $(DEFINES) $(INCPATH) infobar.h -o moc_infobar.cpp

compiler_rcc_make_all: qrc_Resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Resources.cpp
qrc_Resources.cpp: Resources.qrc \
		files/xml/main.xml \
		files/img/stop.png \
		files/img/bg_gui.png \
		files/img/gingancl.png
	/usr/lib64/qt/bin/rcc -name Resources Resources.qrc -o qrc_Resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib64/qt/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		gingapage.h \
		infobar.h \
		page.h \
		util.h \
		menuitem.h \
		gingaproxy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		gingapage.h \
		infobar.h \
		page.h \
		util.h \
		menuitem.h \
		gingaproxy.h \
		ui_mainwindow.h \
		pagexmlparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

page.o: page.cpp page.h \
		util.h \
		menuitem.h \
		gingaproxy.h \
		gingapage.h \
		infobar.h \
		mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o page.o page.cpp

pagexmlparser.o: pagexmlparser.cpp pagexmlparser.h \
		util.h \
		menuitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pagexmlparser.o pagexmlparser.cpp

menuitem.o: menuitem.cpp menuitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o menuitem.o menuitem.cpp

gingaproxy.o: gingaproxy.cpp gingaproxy.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gingaproxy.o gingaproxy.cpp

gingapage.o: gingapage.cpp gingapage.h \
		infobar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gingapage.o gingapage.cpp

infobar.o: infobar.cpp infobar.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o infobar.o infobar.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_page.o: moc_page.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_page.o moc_page.cpp

moc_menuitem.o: moc_menuitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_menuitem.o moc_menuitem.cpp

moc_gingaproxy.o: moc_gingaproxy.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gingaproxy.o moc_gingaproxy.cpp

moc_gingapage.o: moc_gingapage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gingapage.o moc_gingapage.cpp

moc_infobar.o: moc_infobar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_infobar.o moc_infobar.cpp

qrc_Resources.o: qrc_Resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Resources.o qrc_Resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

